version: '3.8'

services:
  # backend
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
  
  # frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
