version: '3.8'

services:
  # backend
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    env_file:
      - .env
  
  # frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
